"use strict";
@@include("_checkWebpSupport.js");
@@include("_displayHints.js");
@@include("_checkboxCheck.js");
@@include("_declarations.js");
@@include("_gameStart.js");
@@include("_prepareToStart.js");
@@include("_startGame.js");
@@include("_startAndStopRun.js");
@@include("_playGame.js");
